DiscountMe/DiscountMe/Controllers/AdvertisersController.cs
using System.Web.Mvc;
using DiscountMe.DAL;

namespace DiscountMe.Controllers {
    public class AdvertisersController : Controller {
        private readonly IUnitOfWork uow;

        public AdvertisersController(IUnitOfWork uoW) {
            uow = uoW;
        }

        //
        // GET: /Advertisers/

        public ActionResult Index() {
            return View();
        }

    }
}

DiscountMe/DiscountMe/Controllers/FaqsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscountMe.Controllers
{
    public class FaqsController : Controller
    {
        //
        // GET: /Faqs/

        public ActionResult Index()
        {
            return View();
        }

    }
}

DiscountMe/DiscountMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>DiscountMe@*-@ViewBag.Title*@</title>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <meta name="description" content=""/>
        <meta name="keywords" content=""/>
        <meta name="copyright" content="Copyright &copy; 2012 IberaSoft"/>
        <meta name="author" content="IberaSoft"/>
        <meta name="robots" content="index, follow"/>
        <meta name="revisit-after" content="7 Days"/>
        <meta name="rating" content="General"/>
        <meta name="distribution" content="Global"/>
        
        <link href="@Url.Content("~/Content/favicon.png")" rel="shortcut icon" type="image/png" />
        <!--[if IE]>
        <link rel="shortcut icon" href="~/Content/favicon.ico" type="image/vnd.microsoft.icon" />
        <![endif]-->
        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
        <link rel="apple-touch-icon-precomposed" href="@Url.Content("~/Content/apple-touch-icon-precomposed.png")" />
        <!-- For first-generation iPad: -->
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="@Url.Content("~/Content/apple-touch-icon-72x72-precomposed.png")" />
        <!-- For iPhone 4 with high-resolution Retina display: -->
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="@Url.Content("~/Content/apple-touch-icon-114x114-precomposed.png")" />
        
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery-ui-1.8.18.custom.css")" rel="stylesheet" type="text/css" /><!--jquery.ui.all.css-->
        <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.18.custom.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/Scripts.js")" type="text/javascript"></script>
    </head>
     <body>
        <div id="wrap">
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Discount Me", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section >
                        <ul id="languages">
                            <li><a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/Images/es.png")" alt="Español" /></a></li>
                            <li><a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/Images/gb.png")" alt="English" /></a></li>
                        </ul>
                    </section>
                    <section id="login">
                        @Html.Partial("_LogOnPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            <li>@Html.ActionLink("Como Usar", "HowItWorks", "Home")</li>
                            <li>@Html.ActionLink("Anunciantes", "Advertisers", "Home")</li>
                            <li>@Html.ActionLink("Ayuda", "Faqs", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p><img src="@Url.Content("~/Images/icono-footer-28x28.png")" alt=""/>DiscountMe&nbsp;</p>
                </div>
                <div class="float-left">
                    <p>&nbsp;<img src="@Url.Content("~/Images/separador.png")" alt=""/>&nbsp;&nbsp;&copy; @DateTime.Now.Year - By&nbsp;<a href="http://www.iberasoft.com"><i>IberaSoft</i></a></p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

DiscountMe/DiscountMe/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    if (Session["Usuario"] != null) {
        <p>
            Bienvenido @Html.ActionLink(User.Identity.Name, "Index", "UserManagement", null, new {@class = "username"})!
            @Html.ActionLink("Salir", "LogOff", "Account")
        </p>
    }
    else {
        <p>
            Bienvenido @Html.ActionLink(User.Identity.Name, "Index", "AdvertisersManagement", null, new {@class = "username"})!
            @Html.ActionLink("Salir", "LogOff", "Account")
        </p>
    }
} else {
    <ul>
        <li>@Html.ActionLink("Nuevo Anunciante", "RegisterNewAdvertiser", "Account", null, new { id = "registerLink", data_dialog_title = "Registration" })</li>
        <li>@Html.ActionLink("Nuevo Usuario", "RegisterNewUser", "Account", null, new { id = "registerLink", data_dialog_title = "Registration" })</li>
        <li>@Html.ActionLink("Acceder", "LogOn", "Account", null, new { id = "logonLink", data_dialog_title = "Identification" })</li>
    </ul>
}